# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: $/dev/null
email: dev@null.com.ar
author: Nico Varaschin
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm a <span class="tooltip">Zombie <span class="tooltiptext">I actually died on the operating table and was revived by the doctors. Literally a Zombie ¯\_(ツ)_/¯ </span></span> Computer Scientist and this is my blog. I'll post my projects and things I find interesting.
  I'm a mix of a Python / Java / Android dev and a Machine Learning and Data Science enthusiast.

description_es: > # this means to ignore newlines until "baseurl:"
  Hola! Soy un Computador Científico <span class="tooltip">Zombie <span class="tooltiptext">Me morí en una operación y los doctores me revivieron. Literalmente un Zombie ¯\_(ツ)_/¯ </span></span> y este es mi blog. Voy a postear mis proyectos y cosas que me parecen interesantes.
  Soy una mezcla de desarrollador Python / Java / Android y un fan de Machine Learning y Data Science.

baseurl: "" # the subpath of your site, e.g. /blog
url: "dev.null.com.ar" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nicovaras
linkedin_username:  nvaraschin
cv:  http://cv.null.com.ar

# Build settings
theme: minima
highlighter: null
gems:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - octopress-video-tag
exclude:
  - Gemfile
  - Gemfile.lock
webrick:
  headers:
    X-I-Am: Nico Varaschin
    X-CV: cv.null.com.ar
    X-Github: github.com/nicovaras
    X-Linkedin: linkedin.com/in/nvaraschin
    X-Email: dev@null.com.ar
    X-ø: µµ

languages: ["en", "es"]
